api:
  port: 8080
db:
  host: "database"
  user: "root"
  pass: "root"
  name: "pointersangle"
  port: 5432
  ssl: "disable"
  tz: "America/Sao_Paulo"
  max_idle_conns: 10
  max_open_conns: 100
  max_life_sec_conn: 5
