version: '3.8'

services:
  database:
    image: postgres:alpine
    container_name: pointersangle-database
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - pointersangle-database:/var/lib/posgresql:rw
    ports:
      - 5432
    networks:
      - backend
    restart: always
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 10

  dbms:
    image: adminer:latest
    container_name: pointersangle-dbms
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8888:8080
    networks:
      - backend
    links:
      - database
    restart: always

  api:
    build: ./
    container_name: pointersangle-api
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - backend
    restart: always

volumes:
  pointersangle-database:

networks:
  backend:
    driver: bridge
