version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: pointersangle-db
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - pointersangle-db:/var/lib/posgresql:rw
    ports:
      - 5432
    networks:
      - backend
    restart: always
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 10

  dbms:
    image: adminer:latest
    container_name: pointersangle-dbms
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8888:8080
    networks:
      - backend
    links:
      - db
    restart: always

  api:
    build: ./
    container_name: pointersangle-api
    volumes:
      - ./config.yml:/go/src/app/config.yml:rw
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - backend
    restart: always

volumes:
  pointersangle-db:

networks:
  backend:
    driver: bridge
